import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { motion } from 'framer-motion'
import { ArrowUpRight, ChevronRight, CircuitBoard, Code2, Cpu, ExternalLink, Layers3, Mail, Menu, MoveRight, Sparkles, X } from 'lucide-react'
import './styles.css'

const nav = ['Home', 'About', 'Skills', 'Projects', 'Experience', 'Certifications', 'Contact']
const Fade = ({ children, className = '' }) => <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .14 }} transition={{ duration: .55 }}>{children}</motion.div>

function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="nav"><a href="#home" className="brand">ABISHEK<span>J</span></a><nav className={open ? 'links open' : 'links'}>{nav.map(x => <a onClick={() => setOpen(false)} key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><button aria-label="Toggle menu" className="menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></header>
}

const SectionTitle = ({ eyebrow, title, text }) => <Fade className="heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</Fade>
const Tag = ({ children }) => <span className="tag">{children}</span>

function Hero() { return <section id="home" className="hero"><div className="hero-copy"><motion.p className="kicker" initial={{opacity:0}} animate={{opacity:1}}>◈ AVAILABLE FOR COLLABORATION</motion.p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.7}}>Hi, I’m <i>Abishek J</i></motion.h1><p className="lead">Mechatronics Engineering Student <b>·</b> Designer <b>·</b> Innovator</p><p className="intro">I build ideas at the intersection of mechanical engineering, automation, AI and digital design.</p><div className="actions"><a className="button primary" href="#projects">Explore My Work <MoveRight size={17}/></a><a className="button" href="#contact">Let’s Connect <ArrowUpRight size={17}/></a></div></div><motion.div className="machine" animate={{y:[-7,7,-7]}} transition={{repeat:Infinity,duration:5,ease:'easeInOut'}}><div className="machine-ring r1"/><div className="machine-ring r2"/><div className="orb"><Cpu size={67}/><span>MECH<br/>TECH</span></div><div className="node n1"><CircuitBoard size={17}/> SYSTEMS</div><div className="node n2"><Sparkles size={17}/> DESIGN</div><div className="node n3"><Code2 size={17}/> BUILD</div></motion.div></section> }

function About() { const stats=[['2024–2028','Engineering Journey'],['3+','Major Projects'],['2+','Industry Internships'],['Multiple','Technical Certifications']]; return <section id="about"><SectionTitle eyebrow="01 / ABOUT" title="Engineering with a human point of view."/><div className="about-grid"><Fade><p className="about-copy">I’m a B.E. Mechatronics Engineering student passionate about designing and building technology-driven solutions. My interests span mechanical design, automation, embedded systems, artificial intelligence and UI/UX. I enjoy transforming ideas into practical prototypes and digital experiences.</p></Fade><div className="stats">{stats.map(([n,l])=><Fade key={l} className="stat"><strong>{n}</strong><span>{l}</span></Fade>)}</div></div></section> }

const skillGroups = [['Engineering & Design',['Fusion 360','CATIA','Blender','CAD Modeling','3D Design','Product Design','Mechanical Design']],['Programming',['Python','Java','C','Embedded Programming']],['AI & Digital Tools',['ChatGPT','Claude','Gemini','AI Tools','Generative AI']],['Electronics & Automation',['Arduino','Raspberry Pi','Sensors','Embedded Systems','PLC','Industrial Automation']],['Design',['Figma','UI/UX Design','Prototyping','Visual Design']]]
function Skills(){return <section id="skills"><SectionTitle eyebrow="02 / CAPABILITIES" title="A multidisciplinary toolkit." text="Combining physical systems with thoughtful digital experiences."/><div className="skills">{skillGroups.map(([t,arr],i)=><Fade className="skill-card" key={t}><span className="index">0{i+1}</span><h3>{t}</h3><div>{arr.map(a=><Tag key={a}>{a}</Tag>)}</div></Fade>)}</div></section>}

const projects=[['VoxChair','Voice-Controlled Smart Wheelchair','Raspberry Pi · Python · Sensors'],['Electronic Compass','Heading Detection System','Embedded · Sensors · C'],['AI Resume Screening','Candidate Success Prediction','AI · Python · Data'],['Industrial Automation','Plant Design Study','PLC · Automation'],['Design Systems','UI/UX Design Projects','Figma · Prototyping']]
function Projects(){return <section id="projects"><SectionTitle eyebrow="03 / SELECTED WORK" title="Built to make ideas move."/><Fade className="feature"><div className="chair-visual"><span className="vis-label">ASSISTIVE MOBILITY / 01</span><div className="wheel w1"/><div className="wheel w2"/><div className="chair-body"/><div className="chair-arm"/><div className="pulse"/></div><div className="feature-body"><span className="eyebrow">FEATURED PROJECT</span><h3>VoxChair — Voice-Controlled Smart Wheelchair</h3><p>An assistive mobility system combining voice control and joystick control to provide intuitive wheelchair navigation.</p><div className="feature-info"><div><small>THE PROBLEM</small><span>Accessible, intuitive mobility control.</span></div><div><small>THE SOLUTION</small><span>Voice + joystick navigation in one system.</span></div></div><div className="tag-row">{['Raspberry Pi','Voice Recognition','Joystick','MCP3008 ADC','Motor Driver','Python'].map(x=><Tag key={x}>{x}</Tag>)}</div><div className="actions"><a className="text-link" href="#contact">View Project <ArrowUpRight size={16}/></a><a className="text-link muted" href="#contact"><Code2 size={16}/> GitHub</a></div></div></Fade><div className="project-grid">{projects.slice(1).map((p,i)=><Fade className="project" key={p[0]}><div className={`project-art art-${i}`}><span>0{i+2}</span><Layers3 size={34}/></div><div><h3>{p[0]}</h3><p>{p[1]}</p><small>{p[2]}</small></div><a href="#contact" aria-label={`View ${p[0]}`}><ArrowUpRight size={18}/></a></Fade>)}</div></section>}

const jobs=[['06.2026 — 07.2026','Hanon Automotive Systems','Production Intern','Industry exposure in automotive production and manufacturing processes, including car compressor module production.'],['INDUSTRIAL INTERNSHIP','UCAL','Industrial Internship','Exposure to automotive manufacturing and bike carburetor assembly processes.'],['06.2026','Dominova','AI Intern','Learning of AI-based resume screening and candidate success prediction systems.']]
function Experience(){return <section id="experience"><SectionTitle eyebrow="04 / EXPERIENCE" title="Learning in real-world systems."/><div className="timeline">{jobs.map(j=><Fade className="job" key={j[1]}><small>{j[0]}</small><div className="dot"/><div><h3>{j[1]}</h3><strong>{j[2]}</strong><p>{j[3]}</p></div></Fade>)}</div></section>}
function Certifications(){const c=['Engineering Design & CAD','AI & Emerging Technologies','Industrial Automation','UI/UX Design Foundations'];return <section id="certifications"><SectionTitle eyebrow="05 / CONTINUOUS LEARNING" title="Always in the lab." text="A growing collection of learning milestones and technical credentials."/><div className="certs">{c.map((x,i)=><Fade key={x} className="cert"><div className="cert-icon">✦</div><small>LEARNING / 2026</small><h3>{x}</h3><p>Credential details available upon request.</p><a href="#contact">View certificate <ChevronRight size={16}/></a></Fade>)}</div></section>}
function Playground(){return <section><SectionTitle eyebrow="06 / DESIGN PLAYGROUND" title="Experiments beyond the blueprint."/><div className="gallery">{['UI INTERFACES','3D OBJECTS','VISUAL SYSTEMS','ENGINEERING DIAGRAMS','POSTER STUDIES','CREATIVE EXPLORATIONS'].map((x,i)=><Fade key={x} className={`tile tile-${i}`}><span>{x}</span><ArrowUpRight size={20}/></Fade>)}</div></section>}
function Marquee(){const tech=['Fusion 360','CATIA','Blender','Python','Java','C','Figma','Arduino','Raspberry Pi','ChatGPT','Claude','Gemini'];return <div className="marquee"><div>{[...tech,...tech].map((x,i)=><span key={i}>✦ {x}</span>)}</div></div>}
function Contact(){return <section id="contact" className="contact"><Fade><span className="eyebrow">07 / GET IN TOUCH</span><h2>Have an idea?<br/><i>Let’s build something.</i></h2><p>I’m always interested in learning, designing and working on innovative engineering and technology projects.</p><div className="contact-links"><a href="mailto:your-email@example.com"><Mail/> Email</a><a href="#contact"><ExternalLink/> LinkedIn</a><a href="#contact"><Code2/> GitHub</a></div></Fade></section>}
function Footer(){return <footer><a href="#home" className="brand">ABISHEK<span>J</span></a><p>Mechatronics Engineering • Design • Automation • AI</p><small>© 2026 Abishek J. All rights reserved.</small></footer>}
function App(){useEffect(()=>{document.documentElement.style.scrollBehavior='smooth'},[]);return <><div className="backdrop"/><Navbar/><main><Hero/><About/><Skills/><Projects/><Experience/><Certifications/><Playground/></main><Marquee/><Contact/><Footer/></>}
createRoot(document.getElementById('root')).render(<App />)
